# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: liangqihang1@hotmail.com
author_name: LIANG QIHANG
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: server
labextension_name: jupyterlab-ai-tutor
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: jupyterlab_ai_tutor
repository: ''
test: false
viewer_name: ''

